name: Terraform AWS deployment of Hazelcast cluster and management center

on:
  push:
    branches: github-actions

jobs:
  build:
    env: 
      AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID :  ${{ secrets.AWS_ACCESS_KEY_ID }}
      SSH_PUBLIC_KEY : ${{ secrets.SSH_PUBLIC_KEY }}
      SSH_PRIVATE_KEY : ${{ secrets.SSH_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name : Set-up Terraform 
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.25
      - run: [ ! -d "~/.ssh" ] && mkdir ~/.ssh
      - run: echo ${SSH_PUBLIC_KEY} > ~/.ssh/id_rsa.pub && echo ${SSH_PRIVATE_KEY} > ~/.ssh/id_rsa

      - run: cd aws && terraform init

      - id: plan
        run: cd aws && terraform plan -no-color

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}